export const GET_CURRENT_WEATHER_STARTED = "GET_CURRENT_WEATHER_STARTED";
export const GET_CURRENT_WEATHER_SUCCESS = "GET_CURRENT_WEATHER_SUCCESS";
export const GET_CURRENT_WEATHER_ERROR = "GET_CURRENT_WEATHER_ERROR";