stages:
  - build

build_ui_image:
  stage: build
  tags:
    - home-server-shell
  script:
    - docker build --tag tuvermind/spa --tag tuvermind/spa:$(head -n1 .version) .
    - docker image prune --force